ers_alvar_Desktop_Programas_eclipse_p2_org.eclipse.equinox.p2.core_cache/uri=file\:/D\:/Users/alvar/Desktop/Programas/eclipse/p2/org.eclipse.equinox.p2.core/cache/
repositories/file\:_D\:_Users_alvar_Desktop_Programas_eclipse_p2_org.eclipse.equinox.p2.core_cache/version=1.0.0
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/description=
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/enabled=true
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/isSystem=false
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/name=org.eclipse.e4.ui update site
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/provider=
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/suffix=artifacts.xml.xz
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/type=org.eclipse.equinox.p2.artifact.repository.simpleRepository
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/uri=https\://download.eclipse.org/e4/snapshots/org.eclipse.e4.ui
repositories/https\:__download.eclipse.org_e4_snapshots_org.eclipse.e4.ui/version=1.0.0
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/count=1
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/description=
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/enabled=true
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/isSystem=false
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/name=The Eclipse Project repository
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/nickname=The Eclipse Project Updates
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/provider=
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/suffix=compositeArtifacts.xml
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/type=org.eclipse.equinox.internal.p2.artifact.repository.CompositeArtifactRepository
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/uri=https\://download.eclipse.org/eclipse/updates/4.25
repositories/https\:__download.eclipse.org_eclipse_updates_4.25/version=1.0.0
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/description=
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/enabled=false
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/isSystem=true
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/name=Eclipse Project Repository for 2022-09
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/provider=
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/suffix=artifacts.xml.xz
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/type=org.eclipse.equinox.p2.artifact.repository.simpleRepository
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/uri=https\://download.eclipse.org/eclipse/updates/4.25/R-4.25-202208311800
repositories/https\:__download.eclipse.org_eclipse_updates_4.25_R-4.25-202208311800/version=1.0.0
repositories/https\:__download